######################################################################
# Automatically generated by qmake (2.01a) ti heinäkuuta 16 23:34:02 2013
######################################################################

TEMPLATE = subdirs
TARGET   = zandemo
SUBDIRS += src
